name: example-environment

dependencies:
  - python=2.7
  - scikit-learn
  - opencv
  - pil
  - numpy
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - pip:
    - git+https://github.com/blaze/dask.git#egg=dask[complete]
